name: Docker Image CI

on: [tag]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Log in to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username onbjerg --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/onbjerg/feather/server:$(git describe --tags --abbrev=0)
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/onbjerg/feather/server:$(git describe --tags --abbrev=0)
