name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Log in to GitHub Package Registry
      run: echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u onbjerg --password-stdin
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/onbjerg/feather/server:$(git describe --tags --abbrev=0)
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/onbjerg/feather/server:$(git describe --tags --abbrev=0)
